name: Hello World Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell script
        run: powershell -ExecutionPolicy Bypass -File ./scripts/GetCoffee.ps1